### ISSUE TITLE
make.sh error

### ISSUE THREAD

**Issue by whut-dg** [JialianW/TraDeS#5]
error: command 'g++' failed with exit status 1

**Comment by xiaoweidao** [comment]
I am also face the problem,can anyone solve it?

**Comment by xiaoweidao** [comment]
`E:\ProgramData\Anaconda3\envs\ganggang\pythonProject\test\TraDeS-master\src\lib\model\networks\DCNv2\src\cpu\dcn_v2_im2col_cpu.cpp : fatal error C1083: Cannot open compiler generated file: '': Invalid argument
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 1`

**Comment by ztb520** [comment]
sudo apt-get install build-essential

**Comment by Hayoung93** [comment]
I solved the same problem by replacing some components in the DCN folder with [https://github.com/lbin/DCNv2/tree/pytorch_1.6](url) according to [https://github.com/CharlesShang/DCNv2/issues/79](url), but a new error occurred :(
Anyway, you could solve the problem related to DCNv2 with torch 1.6.0, cuda 10.1, and cudnn 7.

**Comment by JialianW** [comment]
Please make sure the gcc version is compatible, as described in installation instrctions.

**Comment by pasquale90** [comment]
Mine is 9.3.0, but still having the same error. Should I downgrade it?

**Comment by ayanasser** [comment]
I am working with gcc 8.4.0 as mentioned in the documentation
but the make give me this error

fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
compilation terminated.
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

**Comment by JialianW** [comment]
For the DCN compilation issue, you may refer to JialianW/TraDeS#2, if it still doesn't work after you ensure the GCC version is all set.
